services:
  api:
    build: ./backend
    container_name: enzyme_api
    ports:
      - "7010:8000"
    volumes:
      - ./data:/data
      - ./frontend/dist:/app/static
    environment:
      - ENZYME_DATA_DIR=/data
      - UPLOAD_ASSETS=/data/assets
      - ENZYME_JWT_SECRET=change_this_secret
      - ENZYME_STATIC_DIR=/app/static
    depends_on:
      - mod-smol
      - mod-af2
      - mod-dock
      - mod-md
      - mod-analysis
      - mod-mmpbsa
  nginx:
    image: nginx:1.27-alpine
    container_name: enzyme_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - api
  frontend:
    build: ./frontend
    container_name: enzyme_frontend
    ports:
      - "7006:5500"
    volumes:
      - ./data:/data
      - ./frontend/dist:/app/dist
    depends_on:
      - api
  mod-smol:
    build: ./modules/smol
    container_name: enzyme_mod_smol
    ports:
      - "7001:8001"
    volumes:
      - ./data:/data
    environment:
      - ENZYME_DATA_DIR=/data
  mod-af2:
    build: ./modules/af2
    container_name: enzyme_mod_af2
    ports:
      - "7002:8002"
    volumes:
      - ./data:/data
    environment:
      - ENZYME_DATA_DIR=/data
  mod-dock:
    build: ./modules/dock
    container_name: enzyme_mod_dock
    platform: "linux/amd64"
    ports:
      - "7003:8003"
    volumes:
      - ./data:/data
    environment:
      - ENZYME_DATA_DIR=/data
      - VINA_SERVICE_URL=http://mod-vina:8006/run
    depends_on:
      - mod-vina
  mod-md:
    build: ./modules/md
    container_name: enzyme_mod_md
    platform: "linux/amd64"
    ports:
      - "7004:8004"
    volumes:
      - ./data:/data
    environment:
      - ENZYME_DATA_DIR=/data
  mod-analysis:
    build: ./modules/analysis
    container_name: enzyme_mod_analysis
    ports:
      - "7005:8005"
    volumes:
      - ./data:/data
    environment:
      - ENZYME_DATA_DIR=/data
  mod-mmpbsa:
    build: ./modules/mmpbsa
    container_name: enzyme_mod_mmpbsa
    platform: "linux/amd64"
    ports:
      - "7008:8008"
    volumes:
      - ./data:/data
    environment:
      - ENZYME_DATA_DIR=/data
    entrypoint: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8008"]
  mod-vina:
    build: ./modules/vina
    container_name: enzyme_mod_vina
    platform: "linux/amd64"
    ports:
      - "7016:8006"
    volumes:
      - ./data:/data
    environment:
      - ENZYME_DATA_DIR=/data

volumes:
  data:
    driver: local

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
